=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-domain/prosecutioncasefile-domain-value-schema/src/main/resources/json/schema/parent-bundle-section-reference-data.json.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/parent-bundle-section-reference-data.json",
  "type": "object",
  "description": "Parent Bundle Section Reference Data",
  "properties": {
    "id": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "seqNum": {
      "type": "integer"
    },
    "cpsBundleCode": {
      "type": "string"
    },
    "parentBundleCode": {
      "type": "string"
    },
    "parentBundleDescription": {
      "type": "string"
    },
    "targetSectionCode": {
      "type": "string"
    },
    "unbundleFlag": {
      "type": "boolean"
    },
    "bundleAcceptanceFlag": {
      "type": "boolean"
    },
    "validFrom": {
      "type": "string",
      "format": "date"
    },
    "validTo": {
      "type": "string",
      "format": "date"
    },
    "bundleSections": {
      "$ref": "#/definitions/bundleSection"
    }
  },
  "required": [
    "id",
    "seqNum",
    "cpsBundleCode",
    "parentBundleCode",
    "parentBundleDescription",
    "unbundleFlag",
    "bundleAcceptanceFlag"
  ],
  "additionalProperties": false,
  "definitions": {
    "bundleSection": {
      "type": "array",
      "items": {
        "properties": {
          "seqNum": {
            "type": "integer"
          },
          "bundleSectionCode": {
            "type": "string",
            "maxLength": 10
          },
          "bundleSectionName": {
            "type": "string"
          },
          "splitBundleSubSection": {
            "type": "boolean"
          },
          "targetSectionCode": {
            "type": "string",
            "maxLength": 10
          },
          "validFrom": {
            "type": "string",
            "format": "date"
          },
          "validTo": {
            "type": "string",
            "format": "date"
          }
        },
        "required": [
          "seqNum",
          "bundleSectionCode",
          "bundleSectionName",
          "splitBundleSubSection",
          "targetSectionCode"
        ],
        "additionalProperties": false
      }
    }
  }
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/stub-data/referencedata.get-parent-bundle-sections.json
{
  "id": "7e2f843e-d639-40b3-8611-8015f3a13444",
  "seqNum": 10,
  "cpsBundleCode": "1",
  "parentBundleCode": "IDPC",
  "parentBundleDescription": "IDPC",
  "targetSectionCode": "IDPC",
  "unbundleFlag": true,
  "bundleAcceptanceFlag": true,
  "validFrom": "2019-12-01",
  "validTo": "2021-12-01",
  "bundleSections": [
    {
      "seqNum": 10,
      "bundleSectionCode": "CH",
      "bundleSectionName": "Charges",
      "splitBundleSubSection": false,
      "targetSectionCode": "CH",
      "validFrom": "2020-01-01",
      "validTo": "2020-11-01"
    },
    {
      "seqNum": 20,
      "bundleSectionCode": "CS",
      "bundleSectionName": "Case Summary",
      "splitBundleSubSection": false,
      "targetSectionCode": "CS"
    },
    {
      "seqNum": 30,
      "bundleSectionCode": "KWS",
      "bundleSectionName": "Key Witness Statement",
      "splitBundleSubSection": true,
      "targetSectionCode": "KWS"
    },
    {
      "seqNum": 40,
      "bundleSectionCode": "KE",
      "bundleSectionName": "Key Exhibits",
      "splitBundleSubSection": true,
      "targetSectionCode": "KE"
    },
    {
      "seqNum": 50,
      "bundleSectionCode": "TAI",
      "bundleSectionName": "Transcripts ABE interviews",
      "splitBundleSubSection": true,
      "targetSectionCode": "TAI"
    },
    {
      "seqNum": 60,
      "bundleSectionCode": "SFR",
      "bundleSectionName": "Streamlined Forensic Reports",
      "splitBundleSubSection": true,
      "targetSectionCode": "SFR"
    },
    {
      "seqNum": 70,
      "bundleSectionCode": "PC",
      "bundleSectionName": "Pre Cons",
      "splitBundleSubSection": false,
      "targetSectionCode": "PC"
    }
  ]
}
