=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-domain/prosecutioncasefile-domain-value-schema/src/main/resources/json/schema/prosecutors-reference-data.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/prosecutors-reference-data.json",
  "type": "object",
  "properties": {
    "id": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "sequenceNumber": {
      "type": "integer"
    },
    "majorCreditorCode": {
      "type": "string"
    },
    "shortName": {
      "type": "string"
    },
    "nameWelsh": {
      "type": "string"
    },
    "fullName": {
      "type": "string"
    },
    "address": {
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/address.json"
    },
    "contactEmailAddress": {
      "type": "string"
    },
    "oucode": {
      "type": "string"
    },
    "spiInFlag": {
      "type": "boolean"
    },
    "spiOutFlag": {
      "type": "boolean"
    },
    "sjpFlag": {
      "type": "boolean"
    },
    "cpsFlag": {
      "type": "boolean"
    },
    "informantEmailAddress": {
      "type": "string"
    },
    "prosecutorCategory": {
      "type": "string"
    },
    "standard": {
      "type": "boolean"
    },
    "aocpApproved": {
      "type": "boolean"
    },
    "policeFlag": {
      "type": "boolean"
    }
  },
  "required": [
    "id",
    "sequenceNumber",
    "shortName",
    "fullName",
    "sjpFlag"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/stub-data/referencedata.get-non-sjp-prosecutor.json
{
  "id": "0534ee76-88f6-40e0-ba8f-53588e146675",
  "sequenceNumber": 1,
  "majorCreditorCode": "nonsjp",
  "shortName": "nonsjp",
  "fullName": "nonsjp",
  "nameWelsh": "nonsjp",
  "oucode": "nonsjp",
  "spiInFlag": false,
  "spiOutFlag": true,
  "address": {
    "address1": "6th nonsjp House",
    "postcode": "SW1H 0TL",
    "address2": "42-50 nonsjp Street",
    "address3": "nonsjp"
  },
  "sjpFlag": false
}
