=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-domain/prosecutioncasefile-domain-value-schema/src/main/resources/json/schema/prosecution.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/prosecution.json",
  "type": "object",
  "description": "Prosecution Case File Details",
  "properties": {
    "caseDetails": {
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/case-details.json"
    },
    "defendants": {
      "type": "array",
      "items": {
        "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/defendant.json"
      }
    },
    "channel": {
      "type": "string",
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/pcf-definitions.json#/definitions/channel"
    },
    "listNewHearing": {
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/hearingRequest.json"
    },
    "migrationSourceSystem": {
      "$ref": "http://justice.gov.uk/core/courts/migrationSourceSystem.json"
    },
    "externalId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid",
      "description": "ID originating from the client (SPI or CPPI) for referencing the original message"
    },
    "isCivil": {
      "description": "Marker to indicate that MoJ offence reference data should be used as opposed to criminal offence reference data",
      "type": "boolean"
    },
    "isGroupMember": {
      "description": "Indicates if a case is part of a group of cases within the hearing",
      "type": "boolean"
    },
    "isGroupMaster": {
      "description": "Indicates which case within a group (isGroupMember = true) is the master and should be returned by the backend to the UI",
      "type": "boolean"
    }
  },
  "required": [
    "caseDetails",
    "defendants",
    "channel"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/command-json/prosecutioncasefile.command.initiate-cc-prosecution-requisition-mandatory-fields.json
{
  "caseDetails": {
    "originatingOrganisation": "B01NM00",
    "cpsOrganisation": "A30AB00",
    "caseId": "CASE-ID",
    "initiationCode": "Q",
    "prosecutorCaseReference": "CASE-URN",
    "prosecutor": {
      "informant": "informant",
      "prosecutingAuthority": "prosAut"
    }
  },
  "defendants": [
    {
      "id": "DEFENDANT_ID1",
      "aliasForCorporate": [
        "FakeCompany",
        "RealCompany"
      ],
      "documentationLanguage": "W",
      "hearingLanguage": "W",
      "initialHearing": {
        "courtHearingLocation": "C55BN00",
        "dateOfHearing": "2050-02-04",
        "timeOfHearing": "09:05:01.001"
      },
      "organisationName": "Ministry of Justice",
      "selfDefinedEthnicity": "W1",
      "offences": [
        {
          "offenceCode": "OFCODE12",
          "offenceId": "OFFENCE_ID1",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "2018-09-10",
          "offenceDateCode": 1,
          "offenceLocation": "Croydon",
          "offenceWording": "TV Licence not paid",
          "chargeDate": "2019-01-10",
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "A",
            "alcoholLevelAmount": 100
          }
        }
      ],
      "postingDate": "2018-09-10"
    }
  ],
  "channel": "SPI",
  "externalId": "EXTERNAL_ID"
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/stub-data/prosecutioncasefile.command.initiate-sjp-prosecution.json
{
  "caseDetails": {
    "caseId": "${case.id}",
    "prosecutorCaseReference": "${case.urn}",
    "originatingOrganisation": "123",
    "cpsOrganisation": "A30AB00",
    "initiationCode": "J",
    "prosecutor": {
      "prosecutingAuthority": "${prosecutor.prosecutingAuthority:-GAEAA01}",
      "informant": "Adam"
    }
  },
  "defendants": [
    {
      "id": "${defendant.id}",
      "appliedProsecutorCosts": 200,
      "documentationLanguage": "W",
      "hearingLanguage": "W",
      "prosecutorDefendantReference": "TFL001Defendant01",
      "individual": {
        "personalInformation": {
          "title": "Baron",
          "firstName": "John",
          "lastName": "Smith",
          "address": {
            "address1": "armagaddon house",
            "postcode": "M60 1NW"
          },
          "contactDetails": {
            "home": "0207 000 0000",
            "mobile": "11111 111 111",
            "primaryEmail": "primary@email.com",
            "secondaryEmail": "secondary@email.com",
            "work": "0207 111 1111"
          }
        },
        "selfDefinedInformation": {
          "ethnicity": "W1",
          "gender": "MALE",
          "dateOfBirth": "${defendant.dob:-1990-01-01}",
          "nationality": "${defendant.nationality:-GBR}"
        },
        "nationalInsuranceNumber": "AB123456C"
      },
      "individualAliases": [
        {
          "title": "Mr",
          "firstName": "X",
          "lastName": "Alias1"
        },
        {
          "title": "Mr",
          "firstName": "Y",
          "lastName": "Alias2"
        }
      ],
      "offences": [
        {
          "offenceCode": "${offence.code:-OFCODE12}",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "${offence.committedDate:-2017-11-10}",
          "offenceDateCode": 1,
          "offenceWording": "Duty not paid",
          "chargeDate": "${offence.chargeDate:-2018-02-01}",
          "appliedCompensation": 200,
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "${offence.alcoholRelatedOffence.alcoholLevelMethod:-A}",
            "alcoholLevelAmount": 100
          },
          "backDuty": 340.31,
          "backDutyDateFrom": "2018-04-30",
          "backDutyDateTo": "2018-05-30",
          "vehicleMake": "Ford",
          "vehicleRegistrationMark": "AB11 ABC",
          "prosecutorOfferAOCP": true
        }
      ],
      "postingDate": "2018-09-10"
    }
  ],
  "channel": "${channel}",
  "externalId": "${external.id}"
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-command/prosecutioncasefile-command-api/src/raml/json/prosecutioncasefile.command.initiate-prosecution.json
{
  "caseDetails": {
    "originatingOrganisation": "cps",
    "summonsCode": "summonsCode",
    "statementOfFacts": "statementOfFacts",
    "statementOfFactsWelsh": "statementOfFactsWelsh",
    "caseId": "51cac7fb-387c-4d19-9c80-8963fa8cf222",
    "initiationCode": "H",
    "prosecutorCaseReference": "TVL55117DFXXV",
    "prosecutor": {
      "prosecutingAuthority": "GAEAA01",
      "informant": "Adam"
    }
  },
  "defendants": [
    {
    "documentationLanguage": "W",
    "hearingLanguage": "W",
    "individual": {
      "personalInformation": {
        "title": "Baron",
        "firstName": "John",
        "lastName": "Smith",
        "address": {
          "address1": "armagaddon house",
          "postcode": "M60 1NW"
        },
        "contactDetails": {}
      },
      "selfDefinedInformation": {
        "ethnicity": "white",
        "gender": "MALE"
      }
    },
      "initialHearing": {
        "courtHearingLocation" : "abcd",
        "dateOfHearing": "02-04-1978",
        "timeOfHearing": "9:05",
        "roomId": "af510310-b85f-4a4e-b0b3-9a4ae4cc9cb1",
        "roomName": "Hill East",
        "hearingListingDirection": "Special Need required",
        "hearingDuration": 60,
        "hearingLanguage": "W"
      },
      "offences": [
        {
          "offenceCode": "CA03013",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "2018-09-10",
          "offenceDateCode": 1,
          "offenceLocation": "Croydon",
          "offenceWording": "TV Licence not paid",
          "chargeDate": "2015-04-04",
          "laidDate": "2015-04-04",
          "appliedCompensation": 200
        }
      ],
      "postingDate": "2018-09-10"
    },
    {
      "documentationLanguage": "W",
      "hearingLanguage": "W",
      "individual": {
        "personalInformation": {
          "title": "Baron",
          "firstName": "John",
          "lastName": "Smith",
          "address": {
            "address1": "armagaddon house",
            "postcode": "M60 1NW"
          },
          "contactDetails": {}
        },
        "selfDefinedInformation": {
          "ethnicity": "white",
          "gender": "MALE"
        }
      },
      "offences": [
        {
          "offenceCode": "DA03014",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "2018-09-10",
          "offenceDateCode": 1,
          "offenceLocation": "Croydon",
          "offenceWording": "TV Licence not paid",
          "chargeDate": "2015-04-04",
          "appliedCompensation": 200
        }
      ],
      "postingDate": "2018-09-10"
    }
    ],
  "isCivil": true,
  "isGroupMember": false,
  "isGroupMaster": false,
  "channel": "SPI",
  "externalId": "51cac7fb-387c-4d19-9c80-8963fa8cf333"
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/command-json/prosecutioncasefile.command.initiate-cc-prosecution-corporate-with-new-defendant.json
{
  "caseDetails": {
    "originatingOrganisation": "B01NM00",
    "cpsOrganisation": "A30AB00",
    "otherPartyOfficerInCase": {
      "personalInformation": {
        "address": {
          "address1": "101",
          "address2": "56Police House",
          "address3": "Letsby Avenue",
          "address4": "Avon",
          "postcode": "HA1 2ER"
        },
        "contactDetails": {
          "primaryEmail": "vegaoic@test.dom",
          "work": "0117911911"
        },
        "firstName": "Vega",
        "lastName": "OIC",
        "title": "Baron"
      },
      "policeOfficerRank": "Constable"
    },
    "summonsCode": "A",
    "caseId": "CASE-ID",
    "initiationCode": "C",
    "prosecutorCaseReference": "CASE-URN",
    "caseMarkers": [
      {
        "markerTypeCode": "ABC",
        "markerTypeDescription": "Child Abuse",
        "markerTypeId": "2013c181-7458-4fb2-a637-b596fbe0e781"
      }
    ],
    "prosecutor": {
      "informant": "informant",
      "prosecutingAuthority": "prosAut"
    }
  },
  "defendants": [
    {
      "id": "DEFENDANT_ID1",
      "aliasForCorporate": [
        "FakeCompany",
        "RealCompany"
      ],
      "documentationLanguage": "W",
      "hearingLanguage": "W",
      "custodyStatus": "B",
      "initialHearing": {
        "courtHearingLocation": "C55BN00",
        "dateOfHearing": "2050-02-04",
        "timeOfHearing": "09:05:01.001"
      },
      "organisationName": "Ministry of Justice",
      "selfDefinedEthnicity": "W1",
      "offences": [
        {
          "offenceCode": "OFCODE12",
          "offenceId": "OFFENCE_ID1",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "2018-09-10",
          "offenceCommittedEndDate": "2018-10-10",
          "offenceDateCode": 1,
          "offenceLocation": "Croydon",
          "offenceWording": "TV Licence not paid",
          "chargeDate": "2018-12-10",
          "arrestDate": "2018-11-10",
          "appliedCompensation": 200,
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "A",
            "alcoholLevelAmount": 100
          },
          "vehicleMake": "Ford",
          "vehicleRegistrationMark": "AA11 ABC"
        }
      ],
      "postingDate": "2018-09-10"
    },
    {
      "id": "DEFENDANT_ID2",
      "aliasForCorporate": [
        "FakeCompany",
        "RealCompany"
      ],
      "documentationLanguage": "W",
      "hearingLanguage": "W",
      "custodyStatus": "B",
      "prosecutorDefendantReference" : "A1",
      "initialHearing": {
        "courtHearingLocation": "C55BN00",
        "dateOfHearing": "2050-02-04",
        "timeOfHearing": "09:05:01.001"
      },
      "organisationName": "Ministry of Justice2",
      "selfDefinedEthnicity": "W1",
      "offences": [
        {
          "offenceCode": "OFCODE12",
          "offenceId": "OFFENCE_ID2",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "2018-09-10",
          "offenceCommittedEndDate": "2018-10-10",
          "offenceDateCode": 1,
          "offenceLocation": "Croydon",
          "offenceWording": "TV Licence not paid",
          "chargeDate": "2018-12-10",
          "arrestDate": "2018-11-10",
          "appliedCompensation": 200,
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "A",
            "alcoholLevelAmount": 100
          },
          "vehicleMake": "Ford",
          "vehicleRegistrationMark": "AA11 ABC"
        }
      ],
      "postingDate": "2018-09-10"
    }
  ],
  "channel": "SPI",
  "externalId": "EXTERNAL_ID"
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/command-json/prosecutioncasefile.command.initiate-sjp-prosecution-when-prosecutor-is-valid.json
{
  "caseDetails":{
    "caseId":"CASE-ID",
    "initiationCode":"J",
    "prosecutorCaseReference":"nPGQG9oQw3",
    "originatingOrganisation":"GAEAA01",
    "cpsOrganisation": "A30AB00",
    "prosecutor":{
      "prosecutingAuthority":"GAEAA01",
      "informant":"Venu"
    }
  },
  "defendants":[
    {
      "asn":"asn",
      "documentationLanguage":"E",
      "hearingLanguage":"E",
      "id":"cc71424a-cc98-4dda-828f-eb3e31b075c8",
      "individual":{
        "driverNumber":"AS",
        "nationalInsuranceNumber":"SN123456C",
        "personalInformation":{
          "address":{
            "address1":"Address Line 1",
            "address2":"Address Line 2",
            "address3":"Address Line 3",
            "address4":"Address Line 4",
            "address5":"Address Line 5",
            "postcode":"CR0 1XX"
          },
          "contactDetails":{
            "home":"9991231230",
            "mobile":"9991231230",
            "primaryEmail":"abc@test.com",
            "secondaryEmail":"abc@test.com",
            "work":"9991231230"
          },
          "firstName":"Steve  nothing",
          "lastName":"Reaper",
          "occupation":"TA",
          "occupationCode":666,
          "title":"Baron"
        },
        "selfDefinedInformation":{
          "additionalNationality":"GBR",
          "dateOfBirth":"1999-09-09",
          "ethnicity":"W1",
          "gender":"MALE",
          "nationality":"POL"
        }
      },
      "languageRequirement":"Test no special language needs",
      "numPreviousConvictions":9,
      "offences":[
        {
          "appliedCompensation":0.00,
          "backDuty":0.00,
          "backDutyDateTo":"2019-12-04",
          "chargeDate":"2019-12-04",
          "offenceCode":"CA03013",
          "offenceCommittedDate":"2019-11-04",
          "offenceCommittedEndDate":"2019-12-04",
          "offenceDateCode":4,
          "offenceId":"0572d1d1-97ff-4eb8-87da-601334d543d6",
          "offenceLocation":"Croydon",
          "offenceSequenceNumber":1,
          "offenceWording":"Test Prosecution charge wording",
          "offenceWordingWelsh":"Test Prosecution charge wording in Welsh",
          "statementOfFacts":"Test Prosecution statements of facts"
        }
      ],
      "postingDate":"2019-12-04",
      "prosecutorDefendantReference":"397e6282-21b7-4220-aa75-102dd4569111",
      "specificRequirements":"Test no special needs",
      "appliedProsecutorCosts":20.99
    }
  ],
  "channel":"CPPI",
  "externalId": "EXTERNAL_ID"
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/command-json/prosecutioncasefile.command.initiate-cc-prosecution-cppi-second-message.json
{
  "caseDetails": {
    "originatingOrganisation": "B01NM00",
    "cpsOrganisation": "A30AB00",
    "otherPartyOfficerInCase": {
      "personalInformation": {
        "address": {
          "address1": "101",
          "address2": "56Police House",
          "address3": "Letsby Avenue",
          "address4": "Avon",
          "postcode": "HA1 2ER"
        },
        "contactDetails": {
          "primaryEmail": "vegaoic@test.dom",
          "work": "0117911911"
        },
        "firstName": "Vega",
        "lastName": "OIC",
        "title": "Baron"
      },
      "policeOfficerRank": "Constable"
    },
    "summonsCode": "A",
    "caseId": "CASE-ID",
    "initiationCode": "INITIATION_CODE",
    "prosecutorCaseReference": "CASE-URN",
    "policeSystemId": "00101PoliceCaseSystem",
    "caseMarkers": [
      {
        "markerTypeCode": "ABC",
        "markerTypeDescription": "",
        "markerTypeId": "2013c181-7458-4fb2-a637-b596fbe0e781"
      }
    ],
    "prosecutor": {
      "informant": "informant",
      "prosecutingAuthority": "prosAut"
    },
    "dateReceived": "DATE_RECEIVED"
  },
  "defendants": [
    {
      "id": "DEFENDANT_ID3",
      "prosecutorDefendantReference": "DEFENDANT_REFERENCE3",
      "individualAliases": [
        {
          "title": "Baron",
          "firstName": "John",
          "givenName2": "James",
          "givenName3": "Jerry",
          "lastName": "Smith"
        },
        {
          "title": "Baroness",
          "firstName": "John",
          "lastName": "Smith"
        }
      ],
      "documentationLanguage": "W",
      "hearingLanguage": "W",
      "custodyStatus": "B",
      "bailConditions": "bailConditions",
      "initialHearing": {
        "courtHearingLocation": "C55BN00",
        "dateOfHearing": "2050-02-04",
        "timeOfHearing": "09:05:01.001"
      },
      "individual": {
        "personalInformation": {
          "title": "Baron",
          "firstName": "Alice",
          "lastName": "Smith",
          "address": {
            "address1": "armagaddon house",
            "postcode": "M60 1NW"
          },
          "contactDetails": {}
        },
        "bailConditions": "bailConditions",
        "selfDefinedInformation": {
          "gender": "MALE"
        }
      },
      "offences": [
        {
          "offenceCode": "OFCODE12",
          "offenceId": "OFFENCE_ID3",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "2018-09-10",
          "offenceCommittedEndDate": "2018-10-10",
          "offenceDateCode": 1,
          "offenceLocation": "Croydon",
          "offenceWording": "TV Licence not paid",
          "chargeDate": "2018-10-10",
          "arrestDate": "2018-10-10",
          "appliedCompensation": 200,
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "A",
            "alcoholLevelAmount": 100
          },
          "vehicleMake": "Toyota",
          "vehicleRegistrationMark": "BB11 ABC"
        }
      ],
      "postingDate": "2018-09-10"
    }
  ],
  "channel": "SPI",
  "externalId": "EXTERNAL_ID"
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/command-json/prosecutioncasefile.command.initiate-cc-prosecution-mcc-fixed-earliest-date.json
{
  "caseDetails": {
    "dateReceived": "2018-07-10",
    "trialReceiptType": "Transfer",
    "eitherWayType": "Election of accused",
    "courtReceivedFromCode": "B02NM03",
    "courtReceivedToCode": "B04NM04",
    "classOfCase": "Class 1",
    "originatingOrganisation": "B01NM00",
    "cpsOrganisation": "A30AB00",
    "otherPartyOfficerInCase": {
      "personalInformation": {
        "address": {
          "address1": "101",
          "address2": "56Police House",
          "address3": "Letsby Avenue",
          "address4": "Avon",
          "postcode": "HA1 2ER"
        },
        "contactDetails": {
          "primaryEmail": "vegaoic@test.dom",
          "work": "0117911911"
        },
        "firstName": "Vega",
        "lastName": "OIC",
        "title": "Mr"
      }
    },
    "initiationCode": "O",
    "prosecutor": {
      "prosecutingAuthority": "prosAut"
    },
    "policeForceCode": "1"
  },
  "defendants": [
    {
      "id": "DEFENDANT_ID1",
      "pncIdentifier": "2099/1234567L",
      "croNumber": "SF20/123456M",
      "prosecutorDefendantReference": "TFL001Defendant01",
      "documentationLanguage": "W",
      "hearingLanguage": "W",
      "custodyStatus": "B",
      "numPreviousConvictions": 3,
      "individual": {
        "personalInformation": {
          "title": "Mr",
          "firstName": "John",
          "lastName": "Smith",
          "occupation": "Software Developer",
          "occupationCode": 43,
          "address": {
            "address1": "66 Exeter Street",
            "address2": "line 2",
            "address3": "line 3",
            "address4": "line 4",
            "address5": "line 5",
            "postcode": "M60 1NW"
          },
          "contactDetails": {
            "work": "020111222",
            "home": "020111223",
            "mobile": "07572222943",
            "primaryEmail": "scrooge.mcduck@mail.com",
            "secondaryEmail": "scrooge.mcduck2@mail.com"
          }
        },
        "selfDefinedInformation": {
          "gender": "MALE"
        },
        "bailConditions": "bailConditions",
        "parentGuardianInformation": {
          "selfDefinedEthnicity": "W1",
          "observedEthnicity": "1",
          "gender": "MALE",
          "dateOfBirth": "2015-04-04",
          "personalInformation": {
            "lastName": "Brown"
          }
        }
      },
      "offences": [
        {
          "offenceCode": "OFCODE12",
          "offenceId": "OFFENCE_ID1",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "2018-09-10",
          "offenceCommittedEndDate": "2018-10-10",
          "offenceDateCode": 1,
          "offenceLocation": "Croydon",
          "offenceWording": "TV Licence not paid",
          "chargeDate": "2018-12-04",
          "arrestDate": "2018-12-04",
          "appliedCompensation": 200,
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "A",
            "alcoholLevelAmount": 100
          },
          "vehicleRelatedOffence": {
            "vehicleCode": "O"
          }
        }
      ],
      "postingDate": "2018-09-10"
    }
  ],
  "listNewHearing": {
    "listDefendantRequests": [
      {
        "defendantId": "DEFENDANT_ID1",
        "defendantOffences": [
          "OFFENCE_ID1"
        ]
      }
    ],
    "hearingType": {
      "id": "bf8155e1-90b9-4080-b133-bfbad895d6e4",
      "description": "Trial"
    },
    "hearingDateTimeType": "FIXED",
    "judiciary": [
      {
        "judicialRoleType": {
          "judiciaryType": "Circuit Judge"
        },
        "judicialId": "4e2df740-2822-38cc-be83-4f9cd3324ddc",
        "firstName": "Nicola Jane",
        "lastName": "Smith"
      }
    ],
    "courtCentre": {
      "id": "89592405-c29b-3706-b1d3-b1dd3a08b227",
      "name": "Blackfriars Crown Court",
      "roomId": "60853c27-8a9d-349a-aeb5-7f5049a774dd",
      "roomName": "Courtroom 02"
    },
    "estimatedMinutes": 7560,
    "specialRequirements": [
      "1",
      "11",
      "3"
    ],
    "earliestStartDateTime": "2024-04-25T09:15:00Z",
    "jurisdictionType": "CROWN"
  },
  "channel": "MCC",
  "migrationSourceSystem": {
    "migrationSourceSystemName": "XHIBIT",
    "migrationSourceSystemCaseIdentifier": "XHIBIT-2-HEARINGS"
  }
}
