=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-domain/prosecutioncasefile-domain-value-schema/src/main/resources/json/schema/prosecution.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/prosecution.json",
  "type": "object",
  "description": "Prosecution Case File Details",
  "properties": {
    "caseDetails": {
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/case-details.json"
    },
    "defendants": {
      "type": "array",
      "items": {
        "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/defendant.json"
      }
    },
    "channel": {
      "type": "string",
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/pcf-definitions.json#/definitions/channel"
    },
    "listNewHearing": {
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/hearingRequest.json"
    },
    "migrationSourceSystem": {
      "$ref": "http://justice.gov.uk/core/courts/migrationSourceSystem.json"
    },
    "externalId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid",
      "description": "ID originating from the client (SPI or CPPI) for referencing the original message"
    },
    "isCivil": {
      "description": "Marker to indicate that MoJ offence reference data should be used as opposed to criminal offence reference data",
      "type": "boolean"
    },
    "isGroupMember": {
      "description": "Indicates if a case is part of a group of cases within the hearing",
      "type": "boolean"
    },
    "isGroupMaster": {
      "description": "Indicates which case within a group (isGroupMember = true) is the master and should be returned by the backend to the UI",
      "type": "boolean"
    }
  },
  "required": [
    "caseDetails",
    "defendants",
    "channel"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/command-json/prosecutioncasefile.command.initiate-cc-prosecution1.json
{
  "caseDetails": {
    "originatingOrganisation": "B01NM00",
    "cpsOrganisation": "A30AB00",
    "cpsOrganisationId": "2013c181-7458-4fb2-a637-b596fbe0e781",
    "otherPartyOfficerInCase": {
      "personalInformation": {
        "address": {
          "address1": "101",
          "address2": "56Police House",
          "address3": "Letsby Avenue",
          "address4": "Avon",
          "postcode": "HA1 2ER"
        },
        "contactDetails": {
          "primaryEmail": "vegaoic@test.dom",
          "work": "0117911911"
        },
        "firstName": "Vega",
        "lastName": "OIC",
        "title": "Baron"
      },
      "policeOfficerRank": "Constable"
    },
    "summonsCode": "A",
    "caseId": "CASE-ID",
    "initiationCode": "INITIATION_CODE",
    "prosecutorCaseReference": "CASE-URN",
    "policeSystemId": "00101PoliceCaseSystem",
    "caseMarkers": [
      {
        "markerTypeCode": "ABC",
        "markerTypeDescription": "",
        "markerTypeId": "2013c181-7458-4fb2-a637-b596fbe0e781"
      }
    ],
    "prosecutor": {
      "informant": "informant",
      "prosecutingAuthority": "prosAut"
    },
    "dateReceived": "DATE_RECEIVED"
  },
  "defendants": [
    {
      "id": "DEFENDANT_ID1",
      "asn": "ASN_ID1",
      "prosecutorDefendantReference": "DEFENDANT_REFERENCE1",
      "pncIdentifier": "2099/1234567L",
      "croNumber": "SF20/123456M",
      "documentationLanguage": "W",
      "hearingLanguage": "W",
      "custodyStatus": "B",
      "numPreviousConvictions": 3,
      "initialHearing": {
        "courtHearingLocation": "C55BN00",
        "dateOfHearing": "2050-02-04",
        "timeOfHearing": "09:05:01.001"
      },
      "individual": {
        "personalInformation": {
          "title": "Baron",
          "firstName": "FIRST_NAME_1",
          "lastName": "LAST_NAME_1",
          "occupation": "Software Developer",
          "occupationCode": 43,
          "address": {
            "address1": "66 Exeter Street",
            "address2": "line 2",
            "address3": "line 3",
            "address4": "line 4",
            "address5": "line 5",
            "postcode": "M60 1NW"
          },
          "contactDetails": {
            "work": "020111222",
            "home": "020111223",
            "mobile": "07572222943",
            "primaryEmail": "scrooge.mcduck@mail.com",
            "secondaryEmail": "scrooge.mcduck2@mail.com"
          }
        },
        "selfDefinedInformation": {
          "gender": "MALE",
          "dateOfBirth": "DATE_OF_BIRTH_1"
        },
        "bailConditions": "Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should. 2500 characters",
        "parentGuardianInformation": {
          "selfDefinedEthnicity": "W1",
          "observedEthnicity": "1",
          "gender": "MALE",
          "dateOfBirth": "2015-04-04",
          "personalInformation": {
            "lastName": "Brown"
          }
        }
      },
      "offences": [
        {
          "offenceCode": "OFCODE12",
          "offenceId": "OFFENCE_ID1",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "2018-09-10",
          "offenceCommittedEndDate": "2018-10-10",
          "offenceDateCode": 1,
          "offenceLocation": "Croydon",
          "offenceWording": "TV Licence not paid",
          "chargeDate": "2018-12-04",
          "arrestDate": "2018-12-04",
          "appliedCompensation": 200,
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "A",
            "alcoholLevelAmount": 100
          },
          "vehicleRelatedOffence": {
            "vehicleCode": "O",
            "vehicleRegistrationMark": "AA11 ABC"
          },
          "plea": {
            "pleaDate": "2018-09-11",
            "pleaValue": "GUILTY"
          },
          "verdict": {
            "verdictDate": "2018-09-12",
            "verdictType": {
              "id": "c4ca4238-a0b9-3382-8dcc-509a6f75849b",
              "category": "Guilty",
              "categoryType": "GUILTY"
            }
          }
        }
      ],
      "postingDate": "2018-09-10"
    },
    {
      "id": "DEFENDANT_ID2",
      "asn": "ASN_ID2",
      "prosecutorDefendantReference": "DEFENDANT_REFERENCE2",
      "individualAliases": [
        {
          "title": "Baron",
          "firstName": "John",
          "givenName2": "James",
          "givenName3": "Jerry",
          "lastName": "Smith"
        },
        {
          "title": "Baroness",
          "firstName": "John",
          "lastName": "Smith"
        }
      ],
      "documentationLanguage": "W",
      "hearingLanguage": "W",
      "custodyStatus": "B",
      "bailConditions": "bailConditions",
      "initialHearing": {
        "courtHearingLocation": "C55BN00",
        "dateOfHearing": "2050-02-04",
        "timeOfHearing": "09:05:01.001"
      },
      "individual": {
        "personalInformation": {
          "title": "Baron",
          "firstName": "FIRST_NAME_2",
          "lastName": "LAST_NAME_2",
          "address": {
            "address1": "armagaddon house",
            "postcode": "M60 1NW"
          },
          "contactDetails": {}
        },
        "bailConditions": "bailConditions",
        "selfDefinedInformation": {
          "gender": "MALE",
          "dateOfBirth": "DATE_OF_BIRTH_2"
        }
      },
      "offences": [
        {
          "offenceCode": "OFCODE12",
          "offenceId": "OFFENCE_ID2",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "2018-09-10",
          "offenceCommittedEndDate": "2018-10-10",
          "offenceDateCode": 1,
          "offenceLocation": "Croydon",
          "offenceWording": "TV Licence not paid",
          "chargeDate": "2018-10-10",
          "arrestDate": "2018-10-10",
          "appliedCompensation": 200,
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "A",
            "alcoholLevelAmount": 100
          },
          "vehicleMake": "Toyota",
          "vehicleRegistrationMark": "BB11 ABC"
        }
      ],
      "postingDate": "2018-09-10"
    }
  ],
  "channel": "CPPI",
  "externalId": "EXTERNAL_ID"
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/command-json/prosecutioncasefile.command.initiate-cc-prosecution-requisition-all-fields.json
{
  "caseDetails": {
    "originatingOrganisation": "B01NM00",
    "cpsOrganisation": "A30AB00",
    "otherPartyOfficerInCase": {
      "personalInformation": {
        "address": {
          "address1": "101",
          "address2": "56Police House",
          "address3": "Letsby Avenue",
          "address4": "Avon",
          "postcode": "HA1 2ER"
        },
        "contactDetails": {
          "primaryEmail": "vegaoic@test.dom",
          "work": "0117911911"
        },
        "firstName": "Vega",
        "lastName": "OIC",
        "title": "Baron"
      },
      "policeOfficerRank": "Constable"
    },
    "caseId": "CASE-ID",
    "initiationCode": "Q",
    "prosecutorCaseReference": "CASE-URN",
    "prosecutor": {
      "informant": "informant",
      "prosecutingAuthority": "prosAut"
    }
  },
  "defendants": [
    {
      "id": "DEFENDANT_ID1",
      "prosecutorDefendantReference": "DEFENDANT_REFERENCE1",
      "documentationLanguage": "W",
      "hearingLanguage": "W",
      "custodyStatus": "B",
      "numPreviousConvictions": 3,
      "initialHearing": {
        "courtHearingLocation": "C55BN00",
        "dateOfHearing": "2050-02-04",
        "timeOfHearing": "09:05:01.001"
      },
      "individual": {
        "personalInformation": {
          "title": "Baron",
          "firstName": "John",
          "lastName": "Smith",
          "occupation": "Software Developer",
          "occupationCode": 43,
          "address": {
            "address1": "66 Exeter Street",
            "address2": "line 2",
            "address3": "line 3",
            "address4": "line 4",
            "address5": "line 5",
            "postcode": "M60 1NW"
          },
          "contactDetails": {
            "work": "020111222",
            "home": "020111223",
            "mobile": "07572222943",
            "primaryEmail": "scrooge.mcduck@mail.com",
            "secondaryEmail": "scrooge.mcduck2@mail.com"
          }
        },
        "selfDefinedInformation": {
          "gender": "MALE"
        },
        "parentGuardianInformation": {
          "selfDefinedEthnicity": "W1",
          "observedEthnicity": "1",
          "gender": "MALE",
          "dateOfBirth": "2015-04-04",
          "personalInformation": {
            "lastName": "Brown"
          }
        }
      },
      "offences": [
        {
          "offenceCode": "OFCODE12",
          "offenceId": "OFFENCE_ID1",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "2018-09-10",
          "offenceCommittedEndDate": "2018-10-10",
          "offenceDateCode": 1,
          "offenceLocation": "Croydon",
          "offenceWording": "TV Licence not paid",
          "chargeDate": "2019-01-10",
          "appliedCompensation": 200,
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "A",
            "alcoholLevelAmount": 100
          },
          "vehicleRelatedOffence": {
            "vehicleCode": "O",
            "vehicleRegistrationMark": "AA11 ABC"
          }
        }
      ],
      "postingDate": "2018-09-10"
    },
    {
      "id": "DEFENDANT_ID2",
      "prosecutorDefendantReference": "DEFENDANT_REFERENCE2",
      "individualAliases": [
        {
          "title": "Baron",
          "firstName": "John",
          "givenName2": "James",
          "givenName3": "Jerry",
          "lastName": "Smith"
        },
        {
          "title": "Baroness",
          "firstName": "John",
          "lastName": "Smith"
        }
      ],
      "documentationLanguage": "W",
      "hearingLanguage": "W",
      "custodyStatus": "B",
      "initialHearing": {
        "courtHearingLocation": "C55BN00",
        "dateOfHearing": "2050-02-04",
        "timeOfHearing": "09:05:01.001"
      },
      "individual": {
        "personalInformation": {
          "title": "Baron",
          "firstName": "John",
          "lastName": "Smith",
          "address": {
            "address1": "armagaddon house",
            "postcode": "M60 1NW"
          },
          "contactDetails": {}
        },
        "selfDefinedInformation": {
          "gender": "MALE"
        }
      },
      "offences": [
        {
          "offenceCode": "OFCODE12",
          "offenceId": "OFFENCE_ID2",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "2018-09-10",
          "offenceCommittedEndDate": "2018-10-10",
          "offenceDateCode": 1,
          "offenceLocation": "Croydon",
          "offenceWording": "TV Licence not paid",
          "chargeDate": "2019-01-10",
          "appliedCompensation": 200,
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "A",
            "alcoholLevelAmount": 100
          },
          "vehicleMake": "Toyota",
          "vehicleRegistrationMark": "BB11 ABC"
        }
      ],
      "postingDate": "2018-09-10"
    }
  ],
  "channel": "SPI",
  "externalId": "EXTERNAL_ID"
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/command-json/prosecutioncasefile.command.initiate-cc-prosecution-with-civil-laid-date-arrest-date.json
{
  "caseDetails": {
    "initiationCode": "INITIATION_CODE",
    "prosecutor": {
      "prosecutingAuthority": "prosAut"
    },
    "originatingOrganisation": "GAFTL00",
    "feeStatus": "REFUNDED",
    "dateReceived": "DATE_RECEIVED"
  },
  "defendants": [
    {
      "id": "DEFENDANT_ID1",
      "custodyStatus": "B",
      "individual": {
        "bailConditions": "bailConditions",
        "personalInformation": {
          "address": {
            "address1": "340",
            "address2": "8009 Camden Throughway",
            "postcode": "SW11 1JU"
          },
          "title": "Mr",
          "firstName": "TyshawnTEST",
          "givenName2": "TorreyTest",
          "lastName": "O'Reilly"
        },
        "selfDefinedInformation": {
          "dateOfBirth": "1970-11-11",
          "gender": "NOT_SPECIFIED"
        }
      },
      "documentationLanguage": "E",
      "hearingLanguage": "E",
      "offences": [
        {
          "offenceCode": "RT88007",
          "offenceId": "2013c181-7458-4fb2-a637-b596fbe0e792",
          "offenceSequenceNumber": 1,
          "offenceCommittedEndDate": "2018-10-10",
          "offenceLocation": "Croydon",
          "offenceWording": "TV Licence not paid",

          "arrestDate": "OFFENCE_ARREST_DATE",
          "laidDate": "OFFENCE_LAID_DATE",
          "appliedCompensation": 200,
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "A",
            "alcoholLevelAmount": 100
          },
          "vehicleRelatedOffence": {
            "vehicleCode": "O",
            "vehicleRegistrationMark": "AA11 ABC"
          },
          "plea": {
            "pleaDate": "2018-09-11",
            "pleaValue": "GUILTY"
          },
          "verdict": {
            "verdictDate": "2018-09-12",
            "verdictType": {
              "id": "c4ca4238-a0b9-3382-8dcc-509a6f75849b",
              "category": "Guilty",
              "categoryType": "GUILTY"
            }
          }
        }
      ],
      "initialHearing": {
        "hearingDuration": 20,
        "hearingLanguage": "E",
        "dateOfHearing": "DATE_OF_HEARING",
        "timeOfHearing": "11:11:00.000",
        "courtHearingLocation": "B01LY00",
        "roomId": "9e4932f7-97b2-3010-b942-ddd2624e4dd8"
      },
      "prosecutorDefendantReference": "DEFENDANT_REFERENCE1"
    }
  ],
  "channel": "CIVIL",
  "isCivil": true
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/stub-data/prosecutioncasefile.command.initiate-sjp-prosecution-with-multiple-warnings.json
{
  "caseDetails": {
    "caseId": "${case.id}",
    "prosecutorCaseReference": "${case.urn}",
    "originatingOrganisation": "123",
    "cpsOrganisation": "A30AB00",
    "initiationCode": "J",
    "prosecutor": {
      "prosecutingAuthority": "GAEAA01",
      "informant": "Adam"
    }
  },
  "defendants": [
    {
      "id": "${defendant.id}",
      "appliedProsecutorCosts": 200,
      "documentationLanguage": "W",
      "hearingLanguage": "W",
      "individual": {
        "personalInformation": {
          "title": "Baron",
          "firstName": "John",
          "lastName": "Smith",
          "address": {
            "address1": "armagaddon house",
            "postcode": "M60 1NW"
          },
          "contactDetails": {
            "home": "0207 000 0000",
            "mobile": "11111 111 111",
            "primaryEmail": "primary@email.com",
            "secondaryEmail": "secondary@email.com",
            "work": "0207 111 1111"
          }
        },
        "selfDefinedInformation": {
          "ethnicity": "W1",
          "gender": "MALE",
          "dateOfBirth": "${defendant.dob:-1990-01-01}",
          "nationality": "${defendant.nationality:-GBR}"
        },
        "nationalInsuranceNumber": "AB123456C"
      },
      "offences": [
        {
          "offenceCode": "${offence1.code:-OFCODE12}",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "${offence1.committedDate:-2017-11-10}",
          "offenceDateCode": 1,
          "offenceWording": "TV Licence not paid",
          "chargeDate": "${offence1.chargeDate:-2018-02-01}",
          "appliedCompensation": 200,
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "${offence1.alcoholRelatedOffence.alcoholLevelMethod:-A}",
            "alcoholLevelAmount": 100
          }
        },
        {
          "offenceCode": "${offence2.code:-OFCODE12}",
          "offenceSequenceNumber": 2,
          "offenceCommittedDate": "${offence2.committedDate:-2017-11-10}",
          "offenceDateCode": 1,
          "offenceWording": "TV Licence not paid",
          "chargeDate": "${offence2.chargeDate:-2018-02-01}",
          "appliedCompensation": 200,
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "${offence2.alcoholRelatedOffence.alcoholLevelMethod:-A}",
            "alcoholLevelAmount": 100
          }
        }
      ],
      "postingDate": "2018-09-10"
    }
  ],
  "channel": "CPPI",
  "externalId": "${external.id}"
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/stub-data/prosecutioncasefile.command.initiate-sjp-prosecution-with-company-defendant.json
{
  "caseDetails": {
    "caseId": "${case.id}",
    "prosecutorCaseReference": "${case.urn}",
    "originatingOrganisation": "123",
    "cpsOrganisation": "A30AB00",
    "initiationCode": "J",
    "prosecutor": {
      "prosecutingAuthority": "GAEAA01",
      "informant": "Adam"
    }
  },

  "defendants": [
    {
      "id": "${defendant.id}",
      "appliedProsecutorCosts": 200,
      "documentationLanguage": "W",
      "hearingLanguage": "W",
      "prosecutorDefendantReference": "TFL001Defendant01",
      "organisationName": "Ministry of Justice",
      "address": {
        "address1": "6th Floor Windsor House",
        "address2": "42-50 Victoria Street",
        "address3": "London",
        "address4": "address4",
        "address5": "address5",
        "postcode": "SW1H 0TL"
      },
      "telephoneNumberBusiness": "447824745555",
      "emailAddress1": "email1@gmail.com",
      "emailAddress2": "email2@gmail.com",
      "offences": [
        {
          "offenceCode": "${offence.code:-OFCODE12}",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "${offence.committedDate:-2017-11-10}",
          "offenceDateCode": 1,
          "offenceWording": "Duty not paid",
          "chargeDate": "${offence.chargeDate:-2018-02-01}",
          "appliedCompensation": 200,
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "${offence.alcoholRelatedOffence.alcoholLevelMethod:-A}",
            "alcoholLevelAmount": 100
          },
          "backDuty": 340.31,
          "backDutyDateFrom": "2018-04-30",
          "backDutyDateTo": "2018-05-30",
          "vehicleMake": "Ford",
          "vehicleRegistrationMark": "AB11 ABC"
        }
      ],
      "postingDate": "2018-09-10"
    }
  ],
  "channel": "SPI",
  "externalId": "${external.id}"
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/command-json/prosecutioncasefile.initiate-cc-prosecution-with-mcc-civil-case-with civil-fees.json
{
  "caseDetails": {
    "initiationCode": "INITIATION_CODE",
    "prosecutor": {
      "prosecutingAuthority": "prosAut"
    },
    "originatingOrganisation": "GAFTL00",
    "feeStatus": "REFUNDED",
    "dateReceived": "DATE_RECEIVED"
  },
  "defendants": [
    {
      "id": "DEFENDANT_ID1",
      "individual": {
        "personalInformation": {
          "address": {
            "address1": "340",
            "address2": "8009 Camden Throughway",
            "postcode": "SW11 1JU"
          },
          "title": "Mr",
          "firstName": "TyshawnTEST",
          "givenName2": "TorreyTest",
          "lastName": "O'Reilly"
        },
        "selfDefinedInformation": {
          "dateOfBirth": "1970-11-11",
          "gender": "NOT_SPECIFIED"
        }
      },
      "documentationLanguage": "E",
      "hearingLanguage": "E",
      "offences": [
        {
          "offenceCode": "OFFENCE_CODE",
          "offenceId": "OFFENCE_ID",
          "offenceSequenceNumber": 1,
          "laidDate": "2018-09-10",
          "offenceCommittedEndDate": "2018-10-10",
          "offenceLocation": "Croydon",
          "offenceWording": "TV Licence not paid",
      
          "arrestDate": "2018-12-04",
          "appliedCompensation": 200,
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "A",
            "alcoholLevelAmount": 100
          },
          "vehicleRelatedOffence": {
            "vehicleCode": "O",
            "vehicleRegistrationMark": "AA11 ABC"
          },
          "plea": {
            "pleaDate": "2018-09-11",
            "pleaValue": "GUILTY"
          },
          "verdict": {
            "verdictDate": "2018-09-12",
            "verdictType": {
              "id": "c4ca4238-a0b9-3382-8dcc-509a6f75849b",
              "category": "Guilty",
              "categoryType": "GUILTY"
            }
          }
        }
      ],
      "initialHearing": {
        "hearingDuration": 20,
        "hearingLanguage": "E",
        "dateOfHearing": "DATE_OF_HEARING",
        "timeOfHearing": "11:11:00.000",
        "courtHearingLocation": "B01LY00",
        "roomId": "9e4932f7-97b2-3010-b942-ddd2624e4dd8"
      },
      "prosecutorDefendantReference": "DEFENDANT_REFERENCE1"
    }
  ],
  "channel": "MCC",
  "isCivil": true
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/stub-data/prosecutioncasefile.command.initiate-sjp-prosecution-organisation.json
{
  "caseDetails": {
    "caseId": "${case.id}",
    "prosecutorCaseReference": "${case.urn}",
    "originatingOrganisation": "123",
    "cpsOrganisation": "A30AB00",
    "initiationCode": "J",
    "prosecutor": {
      "prosecutingAuthority": "GAEAA01",
      "informant": "Adam"
    }
  },
  "defendants": [
    {
      "id": "${defendant.id}",
      "appliedProsecutorCosts": 200,
      "documentationLanguage": "W",
      "hearingLanguage": "W",
      "prosecutorDefendantReference": "TFL001Defendant01",
      "address": {
        "address1": "armagaddon house",
        "postcode": "M60 1NW"
      },
      "organisationName": "Susan",
      "individualAliases": [
        {
          "title": "Mr",
          "firstName": "X",
          "lastName": "Alias1"
        },
        {
          "title": "Mr",
          "firstName": "Y",
          "lastName": "Alias2"
        }
      ],
      "offences": [
        {
          "offenceCode": "${offence.code:-OFCODE12}",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "${offence.committedDate:-2017-11-10}",
          "offenceDateCode": 1,
          "offenceWording": "Duty not paid",
          "chargeDate": "${offence.chargeDate:-2018-02-01}",
          "appliedCompensation": 200,
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "${offence.alcoholRelatedOffence.alcoholLevelMethod:-A}",
            "alcoholLevelAmount": 100
          },
          "backDuty": 340.31,
          "backDutyDateFrom": "2018-04-30",
          "backDutyDateTo": "2018-05-30",
          "vehicleMake": "Ford",
          "vehicleRegistrationMark": "AB11 ABC"
        }
      ],
      "postingDate": "2018-09-10"
    }
  ],
  "channel": "CPPI",
  "externalId": "${external.id}"
}
