=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-domain/prosecutioncasefile-domain-value-schema/src/main/resources/json/schema/sjp-defendant.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/sjp-defendant.json",
  "type": "object",
  "description": "Defendant Details",
  "properties": {
    "id": {
      "type": "string",
      "maxLength": 36
    },
    "prosecutorDefendantReference": {
      "type": "string",
      "maxLength": 36
    },
    "asn": {
      "type": "string",
      "description": "Arrest / Summons number",
      "maxLength": 20
    },
    "documentationLanguage": {
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/language.json"
    },
    "hearingLanguage": {
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/language.json"
    },
    "languageRequirement": {
      "type": "string",
      "description": "Notes about the defendant’s language needs, e.g. interpreter details",
      "maxLength": 150
    },
    "specificRequirements": {
      "type": "string",
      "description": "Notes about any help that the defendant may need when attending court – e.g. wheelchair access.",
      "maxLength": 150
    },
    "numPreviousConvictions": {
      "type": "integer",
      "description": "Number of previous conviction cited by prosecutor."
    },
    "individual": {
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/individual.json"
    },
    "offences": {
      "type": "array",
      "minItems": 1,
      "maxItems": 1,
      "items": {
        "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/offence.json"
      }
    },
    "postingDate": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/date",
      "description": "Date on which SJP Notice was posted to the defendant."
    }
  },
  "required": [
    "individual",
    "offences"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-domain/prosecutioncasefile-domain-value-schema/src/main/resources/json/examples/defendant-example.json
{
  "id": "f2426280-f4d7-45cf-9f94-c618a210f7c2",
  "documentationLanguage": "W",
  "hearingLanguage": "W",
  "languageRequirement": "no special language needs",
  "specificRequirements": "no special needs",
  "numPreviousConvictions" : 99,
  "asn" : "arrest/summons",
  "prosecutorDefendantReference": "pderef-1",
  "individual": {
    "driverNumber" : "AS",
    "nationalInsuranceNumber" : "QQ 12 34 56 C",
    "personalInformation": {
      "title": "Baron",
      "firstName": "John",
      "lastName": "Smith",
      "occupation": "Software Developer",
      "occupationCode": 43,
      "address": {
        "address1": "66 Exeter Street",
        "address2": "line 2",
        "address3": "line 3",
        "address4": "line 4",
        "address5": "line 5",
        "postcode": "M60 1NW"
      },
      "contactDetails": {
        "work" : "020111222",
        "home" : "020111223",
        "mobile" : "07572222943",
        "primaryEmail" : "scrooge.mcduck@mail.com",
        "secondaryEmail" : "scrooge.mcduck2@mail.com"
      }
    },
    "selfDefinedInformation": {
      "ethnicity": "white",
      "gender": "MALE",
      "dateOfBirth": "1989-04-18",
      "nationality": "SVK",
      "additionalNationality": "HUN"
    }
  },
  "offences": [
    {
      "offenceCode": "OFCODE12",
      "offenceSequenceNumber": 1,
      "offenceDateCode": 4,
      "offenceCommittedDate": "2015-09-10",
      "offenceCommittedEndDate" : "2016-03-14",
      "offenceLocation" : "London",
      "offenceWording": "TV Licence not paid",
      "offenceWordingWelsh" : "TV Licence not paid (Welsh)",
      "chargeDate": "2016-04-04",
      "appliedCompensation": 1502,
      "statementOfFacts" : "John Doe missed a TV license payment for the 5th time",
      "statementOfFactsWelsh" : "John Doe missed a TV license payment for the 5th time (Welsh)",
      "backDuty" : 3,
      "backDutyDateFrom" : "1987-01-01",
      "backDutyDateTo" : "1999-12-31"
    }
  ],
  "postingDate": "2018-09-10"
}
