=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-event/prosecutioncasefile-event-processor/src/yaml/json/schema/public.prosecutioncasefile.document-bundle-arrived-for-unbundling.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://moj.gov.uk/cps/prosecutioncasefile/domain/event/public.prosecutioncasefile.document-bundle-arrived-for-unbundling",
  "type": "object",
  "properties": {
    "caseId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "prosecutingAuthority": {
      "type": "string"
    },
    "prosecutorDefendantId": {
      "type": "string",
      "maxLength": 36
    },
    "cmsDocumentIdentifier": {
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/cms-document-identifier.json"
    },
    "material": {
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/material.json"
    },
    "receivedDateTime": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/date-time"
    },
    "defendantName": {
      "type": "string"
    }
  },
  "required": [
    "caseId",
    "prosecutorDefendantId",
    "material",
    "cmsDocumentIdentifier",
    "receivedDateTime"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-command/prosecutioncasefile-command-handler/src/test/resources/json/addCpsMaterial.json
{
  "caseId": "51cac7fb-387c-4d19-9c80-8963fa8cf222",
  "prosecutorDefendantId": "TVL_DEF001",
  "cmsDocumentIdentifier": {
    "documentId": "a388efc2-14ff-4e4c-a599-b0934030fed9",
    "materialType":12
  },
  "material": {
    "documentType": "IDPC bundle",
    "fileStoreId": "3042a896-fd3e-478d-bb0e-948dd46191a4",
    "fileType": "application/pdf"
  },
  "cmsDocumentIdentifier": {
    "materialType": 1,
    "documentId": "ABCDEF"
  },
  "receivedDateTime":"2020-02-04T05:27:17.210Z"
}
