=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-event/prosecutioncasefile-event-processor/src/yaml/json/schema/public.stagingprosecutors.cps-serve-ptph-received.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/public.stagingprosecutors.cps-serve-ptph-received.json",
  "type": "object",
  "properties": {
    "submissionId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "submissionStatus": {
      "type": "string",
      "enum": [
        "PENDING",
        "FAILED",
        "REJECTED",
        "SUCCESS",
        "SUCCESS_WITH_WARNINGS",
        "EXPIRED"
      ]
    },
    "prosecutionCaseSubject": {
      "type": "object",
      "properties": {
        "urn": {
          "type": "string",
          "minLength": 1
        },
        "prosecutingAuthority": {
          "type": "string",
          "description": "The OU Code of the prosecuting authority"
        }
      },
      "required": [
        "urn",
        "prosecutingAuthority"
      ],
      "additionalProperties": false
    },
    "cpsDefendant": {
      "description": "Identifies the defendant and offences to which the form is associated to",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "matchingId": {
            "description": "This is randomly generated id for processing only",
            "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
          },
          "prosecutorDefendantId": {
            "description": "A unique reference to a defendant within a prosecution. Provided by the prosecuting authority e.g. DWP",
            "type": "string",
            "maxLength": 36
          },
          "cpsDefendantId": {
            "description": "A unique reference to a defendant within a prosecution. Provided by cps when CPS are prosecuting the case",
            "type": "string",
            "maxLength": 36
          },
          "asn": {
            "description": "A unique reference to a defendant within a prosecution. Provided by the police force and requested from the police by a non police prosecutor e.g. DWP requests from the police",
            "type": "string",
            "maxLength": 21
          },
          "title": {
            "description": "Title by which a defendant is addressed",
            "type": "string"
          },
          "forename": {
            "description": "The first given name of a defendant",
            "type": "string",
            "maxLength": 35
          },
          "forename2": {
            "description": "The second given name of a defendant",
            "type": "string",
            "maxLength": 35
          },
          "forename3": {
            "description": "The third given name of a defendant",
            "type": "string",
            "maxLength": 35
          },
          "surname": {
            "description": "Surname or Family name",
            "type": "string",
            "maxLength": 35
          },
          "dateOfBirth": {
            "description": "The date when the defendant was born",
            "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/date"
          },
          "organisationName": {
            "description": "The name of a defendant that is a legal entity",
            "type": "string"
          },
          "principalCharges": {
            "type": "string"
          },
          "parentGuardianForYouthDefendants": {
            "type": "object",
            "description": "Defendantâ€™s parent or guardian",
            "properties": {
              "title": {
                "type": "string",
                "description": "Title by which a person is addressed",
                "maxLength": 35
              },
              "forename": {
                "type": "string",
                "description": "Given Name",
                "maxLength": 35,
                "pattern": "^(?!.*  ).+",
                "comments": "Alphanumeric no consecutive spaces (i.e. a space can not appear adjacent to another space)."
              },
              "forename2": {
                "type": "string",
                "description": "The second given name of a person, e.g. Ian",
                "maxLength": 35,
                "pattern": "^(?!.*  ).+",
                "comments": "Alphanumeric no consecutive spaces (i.e. a space can not appear adjacent to another space)."
              },
              "forename3": {
                "type": "string",
                "description": "The third given name of a person, e.g. Barry",
                "maxLength": 35,
                "pattern": "^(?!.*  ).+",
                "comments": "Alphanumeric no consecutive spaces (i.e. a space can not appear adjacent to another space)."
              },
              "surname": {
                "type": "string",
                "description": "Surname or Family name, e.g. Brown (CJS DSC v5 3.39 Family Name)",
                "maxLength": 35,
                "pattern": "^(?!.*  ).+",
                "comments": "Alphanumeric no consecutive spaces (i.e. a space can not appear adjacent to another space)."
              },
              "phone": {
                "pattern": "^[0-9+\\ \\-]{10,}$",
                "description": "A home telephone number, including any exchange of location code, at which a person or organisation can be contacted in the UK by telephonic means."
              },
              "relationshipToDefendant": {
                "type": "string",
                "description": "The nature of the relationship to the defendant."
              },
              "email": {
                "type": "string",
                "maxLength": 255
              },
              "address1": {
                "type": "string",
                "description": "Address Line 1 for the defendant",
                "minLength" : 1,
                "maxLength": 35
              },
              "address2": {
                "type": "string",
                "description": "Address Line 2 for the defendant",
                "maxLength": 35
              },
              "address3": {
                "type": "string",
                "description": "Address Line 3 for the defendant",
                "maxLength": 35
              },
              "address4": {
                "type": "string",
                "description": "Address Line 4 for the defendant",
                "maxLength": 35
              },
              "address5": {
                "type": "string",
                "description": "Address Line 5 for the defendant",
                "maxLength": 35
              },
              "postcode": {
                "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/ukGovPostCode",
                "description": "UK Post Code (CGS DSC 5.25)"
              }
            }
          },
          "localAuthorityDetailsForYouthDefendants": {
            "type": "object",
            "description": "Local authority responsible for a youth defendant",
            "properties": {
              "isLookedAfterChild": {
                "type": "boolean",
                "description": "Is the defendant a looked after child"
              },
              "authority": {
                "type": "string",
                "description": "The name of the Local Authority"
              },
              "phone": {
                "pattern": "^[0-9+\\ \\-]{10,}$",
                "description": "A home telephone number, including any exchange of location code, at which a person or organisation can be contacted in the UK by telephonic means."
              },
              "reference": {
                "type": "string",
                "description": "Local authority reference identifier"
              },
              "address1": {
                "type": "string",
                "description": "Address Line 1 for the defendant",
                "minLength" : 1,
                "maxLength": 35
              },
              "address2": {
                "type": "string",
                "description": "Address Line 2 for the defendant",
                "maxLength": 35
              },
              "address3": {
                "type": "string",
                "description": "Address Line 3 for the defendant",
                "maxLength": 35
              },
              "address4": {
                "type": "string",
                "description": "Address Line 4 for the defendant",
                "maxLength": 35
              },
              "address5": {
                "type": "string",
                "description": "Address Line 5 for the defendant",
                "maxLength": 35
              },
              "postcode": {
                "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/ukGovPostCode",
                "description": "UK Post Code (CGS DSC 5.25)"
              },
              "title": {
                "type": "string",
                "description": "Title by which a person is addressed",
                "maxLength": 35
              },
              "forename": {
                "type": "string",
                "description": "Given Name",
                "maxLength": 35,
                "pattern": "^(?!.*  ).+",
                "comments": "Alphanumeric no consecutive spaces (i.e. a space can not appear adjacent to another space)."
              },
              "surname": {
                "type": "string",
                "description": "Surname or Family name, e.g. Brown (CJS DSC v5 3.39 Family Name)",
                "maxLength": 35,
                "pattern": "^(?!.*  ).+",
                "comments": "Alphanumeric no consecutive spaces (i.e. a space can not appear adjacent to another space)."
              },
              "email": {
                "type": "string",
                "maxLength": 255
              }
            }
          }
        }
      }
    },
    "tag": {
      "type": "string"
    },
    "ptphAdvocate": {
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/cps-case-contact.json"
    },
    "trialAdvocate": {
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/cps-case-contact.json"
    },
    "reviewingLawyer": {
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/cps-case-contact.json"
    },
    "prosecutionCaseProgressionOfficer": {
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/cps-case-contact.json"
    },
    "officerInTheCase": {
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/cps-case-contact.json"
    },
    "cpsOffice": {
      "type": "string"
    },
    "draftIndictment": {
      "type": "string"
    },
    "draftIndictmentNotes": {
      "type": "string"
    },
    "summaryOfCircumstances": {
      "type": "string"
    },
    "summaryOfCircumstancesNotes": {
      "type": "string"
    },
    "statementsForPAndICm": {
      "type": "string"
    },
    "statementsForPAndICmNotes": {
      "type": "string"
    },
    "exhibitsForPAndICm": {
      "type": "string"
    },
    "exhibitsForPAndICmNotes": {
      "type": "string"
    },
    "cctv": {
      "type": "string"
    },
    "cctvNotes": {
      "type": "string"
    },
    "streamlinedForensicReport": {
      "type": "string"
    },
    "streamlinedForensicReportNotes": {
      "type": "string"
    },
    "medicalEvidence": {
      "type": "string"
    },
    "medicalEvidenceNotes": {
      "type": "string"
    },
    "expertEvidence": {
      "type": "string"
    },
    "expertEvidenceNotes": {
      "type": "string"
    },
    "badCharacter": {
      "type": "string"
    },
    "badCharacterNotes": {
      "type": "string"
    },
    "hearsay": {
      "type": "string"
    },
    "hearsayNotes": {
      "type": "string"
    },
    "specialMeasures": {
      "type": "string"
    },
    "specialMeasuresNotes": {
      "type": "string"
    },
    "criminalRecord": {
      "type": "string"
    },
    "criminalRecordNotes": {
      "type": "string"
    },
    "victimPersonalStatement": {
      "type": "string"
    },
    "victimPersonalStatementNotes": {
      "type": "string"
    },
    "disclosureManagementDoc": {
      "type": "string"
    },
    "disclosureManagementDocNotes": {
      "type": "string"
    },
    "thirdParty": {
      "type": "string"
    },
    "thirdPartyNotes": {
      "type": "string"
    },
    "reviewDisclosableMaterial": {
      "type": "string"
    },
    "reviewDisclosableMaterialNotes": {
      "type": "string"
    },
    "particularsOfAnyRelatedCriminalProceedings": {
      "type": "string"
    },
    "particularsOfAnyFamily": {
      "type": "string"
    },
    "witnesses": {
      "description": "To provide prosecution witnesses",
      "type": "array",
      "items": {
        "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/witness-ptph.json"
      }
    }
  },
  "required": [
    "submissionId",
    "submissionStatus",
    "prosecutionCaseSubject",
    "cpsDefendant",
    "ptphAdvocate",
    "reviewingLawyer",
    "prosecutionCaseProgressionOfficer",
    "officerInTheCase",
    "cpsOffice",
    "draftIndictment",
    "summaryOfCircumstances",
    "statementsForPAndICm",
    "exhibitsForPAndICm",
    "cctv",
    "streamlinedForensicReport",
    "medicalEvidence",
    "expertEvidence",
    "badCharacter",
    "hearsay",
    "specialMeasures",
    "criminalRecord",
    "victimPersonalStatement",
    "disclosureManagementDoc",
    "thirdParty",
    "reviewDisclosableMaterial"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/stub-data/public.stagingprosecutors.cps-serve-ptph-received_for_asn_only.json
{
  "prosecutionCaseSubject": {
    "prosecutingAuthority": "TheOUC",
    "urn": "%s"
  },
  "submissionId": "e85d2c62-af1f-4674-863a-0891e67e325b",
  "submissionStatus": "PENDING",
  "cpsDefendant": [
    {
      "matchingId": "4b64afd7-686f-4ac8-96f6-ca948d83af3f",
      "asn": "%s",
      "principalCharges": "principal-charges"
    }
  ],
  "tag": "tag",
  "ptphAdvocate": {
    "email": "test@test.com",
    "name": "name",
    "phone": "7778888345"
  },
  "trialAdvocate": {
    "email": "test@test.com",
    "name": "name",
    "phone": "7778888345"
  },
  "reviewingLawyer": {
    "email": "test@test.com",
    "name": "name",
    "phone": "7778888345"
  },
  "prosecutionCaseProgressionOfficer": {
    "email": "test@test.com",
    "name": "name",
    "phone": "7778888345"
  },
  "officerInTheCase": {
    "email": "test@test.com",
    "name": "name",
    "phone": "7778888345"
  },
  "cpsOffice": "Cps Office",
  "draftIndictment": "Y",
  "draftIndictmentNotes": "Draft Indictment Notes",
  "summaryOfCircumstances": "Y",
  "summaryOfCircumstancesNotes": "Summary Of Circumstances Notes",
  "statementsForPAndICm": "Y",
  "statementsForPAndICmNotes": "Statements For P And ICm Notes",
  "exhibitsForPAndICm": "Y",
  "exhibitsForPAndICmNotes": "Exhibits For P And ICm Notes",
  "cctv": "Y",
  "cctvNotes": "Cctv Notes",
  "streamlinedForensicReport": "Y",
  "streamlinedForensicReportNotes": "Streamlined Forensic Report Notes",
  "medicalEvidence": "Y",
  "medicalEvidenceNotes": "Medical Evidence Notes",
  "expertEvidence": "Y",
  "expertEvidenceNotes": "Expert Evidence Notes",
  "badCharacter": "Y",
  "badCharacterNotes": "Bad Character Notes",
  "hearsay": "Y",
  "hearsayNotes": "Hear say Notes",
  "specialMeasures": "Y",
  "specialMeasuresNotes": "Special Measures Notes",
  "criminalRecord": "Y",
  "criminalRecordNotes": "Criminal Record Notes",
  "victimPersonalStatement": "Y",
  "victimPersonalStatementNotes": "Victim Personal Statement Notes",
  "disclosureManagementDoc": "Y",
  "disclosureManagementDocNotes": "Disclosure Management Doc Notes",
  "thirdParty": "Y",
  "thirdPartyNotes": "Third Party Notes",
  "reviewDisclosableMaterial": "Y",
  "reviewDisclosableMaterialNotes": "Review Disclosable Material Notes",
  "particularsOfAnyFamily": "Particulars Of Any Family",
  "particularsOfAnyRelatedCriminalProceedings": "Particulars Of Any Related Criminal Proceedings",
  "witnesses": [
    {
      "firstNameOfIntermediaryKnownAtPtph": "first name",
      "lastNameOfIntermediaryKnownAtPtph": "last name",
      "policeOfficerSubject": {
        "officerInCharge": true,
        "officeCollarNumber": "collar number",
        "officerRank": "Rank1"
      },
      "relevantDisputedIssue": "Issue 1",
      "intermediaryForWitness": "Y",
      "witnessFirstName": "forename",
      "witnessLastName": "abc"
    }
  ]
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/stub-data/public.stagingprosecutors.cps-serve-ptph-received.json
{
  "prosecutionCaseSubject": {
    "prosecutingAuthority": "TheOUC",
    "urn": "caseURN"
  },
  "submissionId": "{SUBMISSION_ID}",
  "submissionStatus": "PENDING",
  "cpsDefendant": [
    {
      "cpsDefendantId": "cps-defendant-id",
      "asn": "cps-asn",
      "dateOfBirth": "1990-12-12",
      "forename": "forename",
      "forename2": "forename2",
      "forename3": "forename3",
      "matchingId": "d5ed8708-2b68-4f57-b492-de3df693047a",
      "organisationName": "organisationName",
      "prosecutorDefendantId": "prosecutorDefendantId",
      "surname": "surname",
      "title": "Mr",
      "principalCharges": "principal-charges"
    }
  ],
  "tag": "tag",
  "ptphAdvocate": {
    "email": "test@test.com",
    "name": "name",
    "phone": "7778888345"
  },
  "trialAdvocate": {
    "email": "test@test.com",
    "name": "name",
    "phone": "7778888345"
  },
  "reviewingLawyer": {
    "email": "test@test.com",
    "name": "name",
    "phone": "7778888345"
  },
  "prosecutionCaseProgressionOfficer": {
    "email": "test@test.com",
    "name": "name",
    "phone": "7778888345"
  },
  "officerInTheCase": {
    "email": "test@test.com",
    "name": "name",
    "phone": "7778888345"
  },
  "cpsOffice": "Cps Office",
  "draftIndictment": "Y",
  "draftIndictmentNotes": "Draft Indictment Notes",
  "summaryOfCircumstances": "Y",
  "summaryOfCircumstancesNotes": "Summary Of Circumstances Notes",
  "statementsForPAndICm": "Y",
  "statementsForPAndICmNotes": "Statements For P And ICm Notes",
  "exhibitsForPAndICm": "Y",
  "exhibitsForPAndICmNotes": "Exhibits For P And ICm Notes",
  "cctv": "Y",
  "cctvNotes": "Cctv Notes",
  "streamlinedForensicReport": "Y",
  "streamlinedForensicReportNotes": "Streamlined Forensic Report Notes",
  "medicalEvidence": "Y",
  "medicalEvidenceNotes": "Medical Evidence Notes",
  "expertEvidence": "Y",
  "expertEvidenceNotes": "Expert Evidence Notes",
  "badCharacter": "Y",
  "badCharacterNotes": "Bad Character Notes",
  "hearsay": "Y",
  "hearsayNotes": "Hear say Notes",
  "specialMeasures": "Y",
  "specialMeasuresNotes": "Special Measures Notes",
  "criminalRecord": "Y",
  "criminalRecordNotes": "Criminal Record Notes",
  "victimPersonalStatement": "Y",
  "victimPersonalStatementNotes": "Victim Personal Statement Notes",
  "disclosureManagementDoc": "Y",
  "disclosureManagementDocNotes": "Disclosure Management Doc Notes",
  "thirdParty": "Y",
  "thirdPartyNotes": "Third Party Notes",
  "reviewDisclosableMaterial": "Y",
  "reviewDisclosableMaterialNotes": "Review Disclosable Material Notes",
  "particularsOfAnyFamily": "Particulars Of Any Family",
  "particularsOfAnyRelatedCriminalProceedings": "Particulars Of Any Related Criminal Proceedings",
  "witnesses": [
    {
      "firstNameOfIntermediaryKnownAtPtph": "first name",
      "intermediaryForWitness": "Y",
      "lastNameOfIntermediaryKnownAtPtph": "last name",
      "policeOfficerSubject": {
        "officerInCharge": true,
        "officeCollarNumber": "collar number",
        "officerRank": "Rank1"
      },
      "relevantDisputedIssue": "Issue 1",
      "witnessFirstName": "forename",
      "witnessLastName": "abc"
    }
  ]
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/stub-data/public.stagingprosecutors.cps-serve-ptph-received_for_defendantdata_only.json
{
  "cpsDefendant": [
    {
      "matchingId": "4b64afd7-686f-4ac8-96f6-ca948d83af3f",
      "cpsDefendantId" : "CPS_DEFENDANT_ID",
      "forename" : "%s",
      "surname": "%s",
      "dateOfBirth": "%s",
      "principalCharges": "principal-charges",
      "localAuthorityDetailsForYouthDefendants": {
        "address1": "address1",
        "authority": "test",
        "email": "test@test.com",
        "forename": "forename",
        "isLookedAfterChild": true,
        "phone": "1234567890",
        "postcode": "G5 0TN",
        "reference": "test",
        "surname": "surname",
        "title": "Mr"
      },
      "parentGuardianForYouthDefendants": {
        "address1": "address1",
        "address2": "address2",
        "email": "test@test.com",
        "forename": "parentForename",
        "phone": "1234567890",
        "postcode": "G5 0TN",
        "relationshipToDefendant": "test",
        "surname": "weterw",
        "title": "Mr"
      }
    }
  ],
  "submissionId": "e85d2c62-af1f-4674-863a-0891e67e325b",
  "submissionStatus": "PENDING",
  "prosecutionCaseSubject": {
    "prosecutingAuthority": "The OU Code of the prosecuting authority",
    "urn": "%s"
  },
  "tag": "tag",
  "ptphAdvocate": {
    "email": "test@test.com",
    "name": "name",
    "phone": "7778888345"
  },
  "trialAdvocate": {
    "email": "test@test.com",
    "name": "name",
    "phone": "7778888345"
  },
  "reviewingLawyer": {
    "email": "test@test.com",
    "name": "name",
    "phone": "7778888345"
  },
  "prosecutionCaseProgressionOfficer": {
    "email": "test@test.com",
    "name": "name",
    "phone": "7778888345"
  },
  "officerInTheCase": {
    "email": "test@test.com",
    "name": "name",
    "phone": "7778888345"
  },
  "cpsOffice": "Cps Office",
  "draftIndictment": "Y",
  "summaryOfCircumstances": "Y",
  "statementsForPAndICm": "Y",
  "exhibitsForPAndICm": "Y",
  "cctv": "Y",
  "cctvNotes": "Cctv Notes",
  "streamlinedForensicReport": "Y",
  "medicalEvidence": "Y",
  "expertEvidence": "Y",
  "badCharacter": "Y",
  "hearsay": "Y",
  "specialMeasures": "Y",
  "criminalRecord": "Y",
  "victimPersonalStatement": "Y",
  "disclosureManagementDoc": "Y",
  "thirdParty": "Y",
  "reviewDisclosableMaterial": "Y",
  "witnesses": [
    {
      "firstNameOfIntermediaryKnownAtPtph": "first name",
      "lastNameOfIntermediaryKnownAtPtph": "last name",
      "policeOfficerSubject": {
        "officerInCharge": true,
        "officeCollarNumber": "collar number",
        "officerRank": "Rank1"
      },
      "relevantDisputedIssue": "Issue 1",
      "witnessFirstName": "forename",
      "witnessLastName": "abc"
    }
  ]
}
