=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-command/prosecutioncasefile-command-api/src/raml/json/schema/prosecutioncasefile.plead-online.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://moj.gov.uk/cps/prosecutioncasefile/command/api/plead-online.json",
  "type": "object",
  "properties": {
    "caseId": {
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/plea/json/schemas/definitions.json#/definitions/uuid"
    },
    "urn": {
      "type": "string"
    },
    "defendantId": {
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/plea/json/schemas/definitions.json#/definitions/uuid"
    },
    "initiationCode": {
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/plea/json/schemas/initiation-code.json"
    },
    "personalDetails": {
      "id": "http://cpp.moj.gov.uk/prosecution/casefile/plea/json/schemas/personal-details.json",
      "type": "object",
      "properties": {
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "address": {
          "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/plea/json/schemas/address.json"
        },
        "contactDetails": {
          "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/plea/json/schemas/contact-details.json",
          "required": [
            "email"
          ]
        },
        "dateOfBirth": {
          "type": "string"
        },
        "nationalInsuranceNumber": {
          "type": "string"
        },
        "driverNumber": {
          "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/plea/json/schemas/definitions.json#/definitions/dvlaDriverLicence"
        },
        "driverLicenceDetails": {
          "type": "string"
        }
      },
      "required": [
        "firstName",
        "lastName",
        "address",
        "contactDetails",
        "dateOfBirth"
      ],
      "additionalProperties": false
    },
    "legalEntityDefendant": {
      "id": "http://cpp.moj.gov.uk/prosecution/casefile/plea/json/schemas/legal-entity-defendant.json",
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "address": {
          "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/plea/json/schemas/address.json"
        },
        "contactDetails": {
          "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/plea/json/schemas/contact-details.json",
          "required": [
            "email"
          ]
        },
        "incorporationNumber": {
          "type": "string"
        },
        "position": {
          "id": "http://cpp.moj.gov.uk/prosecution/casefile/plea/json/schemas/position.json",
          "type": "string"
        }
      },
      "required": [
        "name",
        "address",
        "contactDetails"
      ],
      "additionalProperties": false
    },
    "offences": {
      "type": "array",
      "items": {
        "id": "http://cpp.moj.gov.uk/prosecution/casefile/plea/json/schemas/offence.json",
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "plea": {
            "id": "http://cpp.moj.gov.uk/prosecution/casefile/plea/json/schemas/plea-type.json",
            "type": "string",
            "enum": [
              "NOT_GUILTY",
              "GUILTY"
            ]
          },
          "mitigation": {
            "type": "string"
          },
          "notGuiltyBecause": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "plea"
        ],
        "additionalProperties": false
      }
    },
    "comeToCourt": {
      "type": "boolean"
    },
    "witnessDispute": {
      "type": "string"
    },
    "witnessDetails": {
      "type": "string"
    },
    "outstandingFines": {
      "type": "boolean"
    },
    "interpreterLanguage": {
      "type": "string"
    },
    "speakWelsh": {
      "type": "boolean"
    },
    "unavailability": {
      "type": "string"
    },
    "financialMeans": {
      "id": "http://cpp.moj.gov.uk/prosecution/casefile/plea/json/schemas/financial-means.json",
      "type": "object",
      "properties": {
        "defendantId": {
          "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/plea/json/schemas/definitions.json#/definitions/uuid"
        },
        "income": {
          "id": "http://cpp.moj.gov.uk/prosecution/casefile/plea/json/schemas/income.json",
          "type": "object",
          "properties": {
            "amount": {
              "type": "number"
            },
            "frequency": {
              "id": "http://cpp.moj.gov.uk/prosecution/casefile/plea/json/schemas/frequency.json",
              "type": "string",
              "enum": [
                "WEEKLY",
                "FORTNIGHTLY",
                "MONTHLY",
                "YEARLY"
              ]
            }
          },
          "required": [
            "amount",
            "frequency"
          ],
          "additionalProperties": false
        },
        "benefits": {
          "id": "http://cpp.moj.gov.uk/prosecution/casefile/plea/json/schemas/benefits.json",
          "type": "object",
          "properties": {
            "claimed": {
              "type": "boolean"
            },
            "type": {
              "type": "string"
            },
            "deductPenaltyPreference": {
              "type": "boolean"
            }
          },
          "required": [
            "claimed"
          ],
          "additionalProperties": false
        },
        "employmentStatus": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "legalEntityFinancialMeans": {
      "id": "http://cpp.moj.gov.uk/prosecution/casefile/plea/json/schemas/legal-entity-financial-means.json",
      "type": "object",
      "properties": {
        "outstandingFines": {
          "type": "boolean"
        },
        "tradingMoreThan12Months": {
          "type": "boolean"
        },
        "numberOfEmployees": {
          "type": "integer"
        },
        "grossTurnover": {
          "type": "number"
        },
        "netTurnover": {
          "type": "number"
        }
      },
      "additionalProperties": false
    },
    "employer": {
      "id": "http://cpp.moj.gov.uk/prosecution/casefile/plea/json/schemas/employer.json",
      "type": "object",
      "properties": {
        "employeeReference": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        },
        "address": {
          "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/plea/json/schemas/address.json"
        }
      },
      "required": [
        "name",
        "address"
      ],
      "additionalProperties": false
    },
    "outgoings": {
      "type": "array",
      "items": {
        "id": "http://cpp.moj.gov.uk/prosecution/casefile/plea/json/schemas/outgoing.json",
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          },
          "amount": {
            "type": "number"
          }
        },
        "additionalProperties": false
      }
    },
    "disabilityNeeds": {
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/plea/json/schemas/disability-needs.json"
    },
    "pcqId": {
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/plea/json/schemas/definitions.json#/definitions/uuid"
    }
  },
  "oneOf": [
    {
      "required": [
        "caseId",
        "defendantId",
        "personalDetails",
        "offences",
        "initiationCode"
      ]
    },
    {
      "required": [
        "caseId",
        "defendantId",
        "legalEntityDefendant",
        "offences",
        "initiationCode"
      ]
    }
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-command/prosecutioncasefile-command-api/src/test/resources/test.json
{
  "caseId": "87350bfb-acfd-4199-8ec2-62635eb504ad",
  "defendantId": "62494f69-dd6c-4f76-9518-a1f95e322281",
  "urn": "SNI2937",
  "initiationCode": "Q",
  "personalDetails": {
    "firstName": "Rob",
    "lastName": "Smith",
    "dateOfBirth": "1977-11-02",
    "address": {
      "address1": "xTvOdwOB8i",
      "address2": "56Police House",
      "address3": "StreetDescription",
      "address4": "Locality2O",
      "address5": "TownD",
      "postcode": "TW14 9XD"
    },
    "contactDetails": {
      "email": "robert@gmail.com",
      "home": "09998021888",
      "work": "0917894278022",
      "mobile": "09998021889"
    }
  },
  "offences": [
    {
      "id": "e8e216cc-13d1-49d0-acf2-f7f7e40a8178",
      "plea": "GUILTY",
      "title": "Fail to carry an animal on a moving escalator on the Tyne and Wear Metro",
      "mitigation": "test"
    }
  ],
  "comeToCourt": true,
  "speakWelsh": false,
  "disabilityNeeds": {
    "needed": false
  },
  "outstandingFines": false,
  "financialMeans": {
    "income": {
      "frequency": "MONTHLY",
      "amount": 2000
    },
    "benefits": {
      "claimed": false
    },
    "employmentStatus": "EMPLOYED"
  }
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/command-json/prosecutioncasefile.command.plead-online-legal-entity-defendant.json
{
"caseId": "CASE_ID",
"defendantId": "DEFENDANT_ID",
"initiationCode": "INITIATION_CODE",
"legalEntityDefendant": {
"name": "Testy",
"address": {
"address1": "14 Tottenham Court Road",
"address2": "London",
"address3": "England",
"address4": "UK",
"address5": "Greater London",
"postcode": "W1T 1JY"
},
"contactDetails": {
"home": "0208000888",
"mobile": "07890123123",
"email": "criminal@gmail.com"
}
},
"legalEntityFinancialMeans": {
"outstandingFines": false,
"numberOfEmployees": 10,
"tradingMoreThan12Months": false,
"grossTurnover": 5000.50,
"netTurnover":1000.50
},
"offences": [
{
"id": "ecf30a03-8a17-4fc5-81d2-b72ac0a13d17",
"plea": "NOT_GUILTY",
"notGuiltyBecause": "I was forced to do it"
}
],
"witnessDispute": "They are lying",
"witnessDetails": "My mate Dave",
"outstandingFines": false,
"unavailability": "I'm on holiday November 17 to 19",
"interpreterLanguage": "French",
"speakWelsh": false,
"outgoings": [
{
"description": "Accommodation",
"amount": 50
},
{
"description": "Council Tax",
"amount": 50
},
{
"description": "Household bills",
"amount": 50
},
{
"description": "Travel expenses",
"amount": 50
},
{
"description": "Child maintenance",
"amount": 50
}
]
}
