=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-command/prosecutioncasefile-command-handler/src/raml/json/schema/prosecutioncasefile.command.add-application-court-document.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/core/courts/add-application-court-document.json",
  "type": "object",
  "properties": {
    "materialId":{
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "courtDocument": {
     "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/courtDocument.json#"
    },
    "isUnbundledDocument": {
      "type": "boolean",
      "default": false
    },
    "isCpsCase": {
      "type": "boolean"
    },
    "fileStoreId": {
      "type": "string"
    },
    "applicationId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    }
  },
  "required": [
    "materialId",
    "courtDocument",
    "fileStoreId",
    "applicationId"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-command/prosecutioncasefile-command-handler/src/raml/json/prosecutioncasefile.command.add-application-court-document.json
{
  "courtDocument": {
    "courtDocumentId": "3aa6d35d-70c3-45fb-a05e-bfedbce16412",
    "name": "SJP Notice",
    "documentTypeId": "0bb7b276-9dc0-4af2-83b9-f4acef0c7898",
    "documentTypeDescription": "SJP Notice",
    "mimeType": "pdf",
    "materials": [
      {
        "id": "5e1cc18c-76dc-47dd-99c1-d6f87385edf1"
      }
    ],
    "containsFinancialMeans": false,
    "sendToCps": false
  },
  "fileStoreId" : "2279b2c3-b0d3-4889-ae8e-1ecc20c39e28",
  "materialId" : "2279b2c3-b0d3-4889-ae8e-1ecc20c39e29",
  "applicationId" : "2279b2c3-b0d3-4889-ae8e-1ecc20c39e39"
}
